### ISSUE TITLE
Heightcoding: please forward complaint to management

### ISSUE THREAD

**Issue by pjanetzek** [melowntech/vts-mapproxy#27]
``` 
               LOGONCE(warn3) << "2D polygon heightcoding not implemented. "
                    "You may complain to the management.";
```
Either that or I will try to implement this soon :)  Also for exact lines matching on terrain it will probably be necessary to insert vertices at the intersection with surface mesh edges.

**Comment by vaclavblazek** [comment]
Wait, heighcoding is related to vector data, not raster data.

**Comment by pjanetzek** [comment]
yes I'm aware of that - my goal is to have OSM vector features tightly mapped onto the terrain

**Comment by pjanetzek** [comment]
I've implemented this previously with cgal on a custom tile-builder backend, but unfortunately lost the code due to a company shutdown

**Comment by vaclavblazek** [comment]
OK, however we never implemented polygon, didn't need it. I'm affraid there are no resource at our side to implement it now.

(FYI, the "you may complain ti the management" is a inner joke -- our manager implemented the heightcoding functionality and skipped stuff not needed at that time.)

**Comment by pjanetzek** [comment]
yea ok - I see :) please close this issue

**Comment by vaclavblazek** [comment]
OK, closing as requested.
